/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './profile-edit.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../auth/auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import15 from '@angular/forms/src/directives/ng_control_status';
import * as import16 from '@angular/forms/src/directives/default_value_accessor';
import * as import17 from '@angular/forms/src/directives/validators';
import * as import18 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/forms/src/validators';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/control_container';
var renderType_ProfileEditComponent_Host:import0.RenderComponentType = (null as any);
class _View_ProfileEditComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ProfileEditComponent_0_4:import3.ProfileEditComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ProfileEditComponent_Host0,renderType_ProfileEditComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-profileedit',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ProfileEditComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ProfileEditComponent_0_4 = new import3.ProfileEditComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._ProfileEditComponent_0_4,[],compView_0);
    compView_0.create(this._ProfileEditComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ProfileEditComponent) && (0 === requestNodeIndex))) { return this._ProfileEditComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ProfileEditComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProfileEditComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ProfileEditComponent_Host === (null as any))) { (renderType_ProfileEditComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_ProfileEditComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ProfileEditComponentNgFactory:import11.ComponentFactory<import3.ProfileEditComponent> = new import11.ComponentFactory<import3.ProfileEditComponent>('app-profileedit',viewFactory_ProfileEditComponent_Host0,import3.ProfileEditComponent);
const styles_ProfileEditComponent:any[] = [];
var renderType_ProfileEditComponent:import0.RenderComponentType = (null as any);
class _View_ProfileEditComponent0 extends import1.AppView<import3.ProfileEditComponent> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import12.NgIf;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ProfileEditComponent0,renderType_ProfileEditComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-md-8 col-md-offset-2');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import13.TemplateRef_(this._appEl_2,viewFactory_ProfileEditComponent1);
    this._NgIf_2_6 = new import12.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import12.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.myForm;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ProfileEditComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ProfileEditComponent> {
  if ((renderType_ProfileEditComponent === (null as any))) { (renderType_ProfileEditComponent = viewUtils.createRenderComponentType('C:/Users/Silvia/OneDrive/Bakalárka/Project/assets/app/profile/profile-edit.component.html',0,import10.ViewEncapsulation.None,styles_ProfileEditComponent,{})); }
  return new _View_ProfileEditComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ProfileEditComponent1 extends import1.AppView<any> {
  _el_0:any;
  _FormGroupDirective_0_3:import14.FormGroupDirective;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import15.NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _DefaultValueAccessor_11_3:import16.DefaultValueAccessor;
  _RequiredValidator_11_4:import17.RequiredValidator;
  _NG_VALIDATORS_11_5:any[];
  _NG_VALUE_ACCESSOR_11_6:any[];
  _FormControlName_11_7:import18.FormControlName;
  _NgControl_11_8:any;
  _NgControlStatus_11_9:import15.NgControlStatus;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _DefaultValueAccessor_22_3:import16.DefaultValueAccessor;
  _RequiredValidator_22_4:import17.RequiredValidator;
  _NG_VALIDATORS_22_5:any[];
  _NG_VALUE_ACCESSOR_22_6:any[];
  _FormControlName_22_7:import18.FormControlName;
  _NgControl_22_8:any;
  _NgControlStatus_22_9:import15.NgControlStatus;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ProfileEditComponent1,renderType_ProfileEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'form',(null as any));
    this._FormGroupDirective_0_3 = new import14.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_0_4 = this._FormGroupDirective_0_3;
    this._NgControlStatusGroup_0_5 = new import15.NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-xs-12');
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','form-group');
    this._text_7 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'label',(null as any));
    this.renderer.setElementAttribute(this._el_8,'for','firstName');
    this._text_9 = this.renderer.createText(this._el_8,'First name',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_6,'input',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','form-control');
    this.renderer.setElementAttribute(this._el_11,'formControlName','firstName');
    this.renderer.setElementAttribute(this._el_11,'id','firstName');
    this.renderer.setElementAttribute(this._el_11,'required','');
    this.renderer.setElementAttribute(this._el_11,'type','text');
    this._DefaultValueAccessor_11_3 = new import16.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_11));
    this._RequiredValidator_11_4 = new import17.RequiredValidator();
    this._NG_VALIDATORS_11_5 = [this._RequiredValidator_11_4];
    this._NG_VALUE_ACCESSOR_11_6 = [this._DefaultValueAccessor_11_3];
    this._FormControlName_11_7 = new import18.FormControlName(this._ControlContainer_0_4,this._NG_VALIDATORS_11_5,(null as any),this._NG_VALUE_ACCESSOR_11_6);
    this._NgControl_11_8 = this._FormControlName_11_7;
    this._NgControlStatus_11_9 = new import15.NgControlStatus(this._NgControl_11_8);
    this._text_12 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._text_13 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','col-xs-12');
    this._text_16 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','form-group');
    this._text_18 = this.renderer.createText(this._el_17,'\n                    ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'label',(null as any));
    this.renderer.setElementAttribute(this._el_19,'for','lastName');
    this._text_20 = this.renderer.createText(this._el_19,'Last name',(null as any));
    this._text_21 = this.renderer.createText(this._el_17,'\n                    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_17,'input',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','form-control');
    this.renderer.setElementAttribute(this._el_22,'formControlName','lastName');
    this.renderer.setElementAttribute(this._el_22,'id','lastName');
    this.renderer.setElementAttribute(this._el_22,'required','');
    this.renderer.setElementAttribute(this._el_22,'type','text');
    this._DefaultValueAccessor_22_3 = new import16.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_22));
    this._RequiredValidator_22_4 = new import17.RequiredValidator();
    this._NG_VALIDATORS_22_5 = [this._RequiredValidator_22_4];
    this._NG_VALUE_ACCESSOR_22_6 = [this._DefaultValueAccessor_22_3];
    this._FormControlName_22_7 = new import18.FormControlName(this._ControlContainer_0_4,this._NG_VALIDATORS_22_5,(null as any),this._NG_VALUE_ACCESSOR_22_6);
    this._NgControl_22_8 = this._FormControlName_22_7;
    this._NgControlStatus_22_9 = new import15.NgControlStatus(this._NgControl_22_8);
    this._text_23 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._text_24 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._text_25 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','row');
    this._text_28 = this.renderer.createText(this._el_27,'\n            ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'div',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','col-xs-12');
    this._text_30 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'button',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','btn btn-success');
    this.renderer.setElementAttribute(this._el_31,'type','submit');
    this._text_32 = this.renderer.createText(this._el_31,'Save',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_29,'a',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','btn btn-danger');
    this._text_35 = this.renderer.createText(this._el_34,'Cancel',(null as any));
    this._text_36 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._text_37 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'ngSubmit',this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'submit',this.eventHandler(this._handle_submit_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'reset',this.eventHandler(this._handle_reset_0_2.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_0_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_11,'input',this.eventHandler(this._handle_input_11_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_11,'blur',this.eventHandler(this._handle_blur_11_1.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_22,'input',this.eventHandler(this._handle_input_22_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_22,'blur',this.eventHandler(this._handle_blur_22_1.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_34,'click',this.eventHandler(this._handle_click_34_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.DefaultValueAccessor) && (11 === requestNodeIndex))) { return this._DefaultValueAccessor_11_3; }
    if (((token === import17.RequiredValidator) && (11 === requestNodeIndex))) { return this._RequiredValidator_11_4; }
    if (((token === import20.NG_VALIDATORS) && (11 === requestNodeIndex))) { return this._NG_VALIDATORS_11_5; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (11 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_11_6; }
    if (((token === import18.FormControlName) && (11 === requestNodeIndex))) { return this._FormControlName_11_7; }
    if (((token === import22.NgControl) && (11 === requestNodeIndex))) { return this._NgControl_11_8; }
    if (((token === import15.NgControlStatus) && (11 === requestNodeIndex))) { return this._NgControlStatus_11_9; }
    if (((token === import16.DefaultValueAccessor) && (22 === requestNodeIndex))) { return this._DefaultValueAccessor_22_3; }
    if (((token === import17.RequiredValidator) && (22 === requestNodeIndex))) { return this._RequiredValidator_22_4; }
    if (((token === import20.NG_VALIDATORS) && (22 === requestNodeIndex))) { return this._NG_VALIDATORS_22_5; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (22 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_22_6; }
    if (((token === import18.FormControlName) && (22 === requestNodeIndex))) { return this._FormControlName_22_7; }
    if (((token === import22.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_8; }
    if (((token === import15.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_9; }
    if (((token === import14.FormGroupDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._FormGroupDirective_0_3; }
    if (((token === import23.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._ControlContainer_0_4; }
    if (((token === import15.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgControlStatusGroup_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = this.parent.context.myForm;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._FormGroupDirective_0_3.form = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_0_3.ngOnChanges(changes); }
    const currVal_12:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._RequiredValidator_11_4.required = currVal_12;
      this._expr_12 = currVal_12;
    }
    changes = (null as any);
    const currVal_14:any = 'firstName';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._FormControlName_11_7.name = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    if ((changes !== (null as any))) { this._FormControlName_11_7.ngOnChanges(changes); }
    const currVal_23:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._RequiredValidator_22_4.required = currVal_23;
      this._expr_23 = currVal_23;
    }
    changes = (null as any);
    const currVal_25:any = 'lastName';
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._FormControlName_22_7.name = currVal_25;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_25,currVal_25);
      this._expr_25 = currVal_25;
    }
    if ((changes !== (null as any))) { this._FormControlName_22_7.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatusGroup_0_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_0_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_0_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_0,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_0_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_0,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_0_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_0,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_0_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_0,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = (this._RequiredValidator_11_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementAttribute(this._el_11,'required',((currVal_13 == (null as any))? (null as any): currVal_13.toString()));
      this._expr_13 = currVal_13;
    }
    const currVal_15:any = this._NgControlStatus_11_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_11,'ng-untouched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_11_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_11,'ng-touched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_11_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_11,'ng-pristine',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_11_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_11,'ng-dirty',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_11_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_11,'ng-valid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_11_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_11,'ng-invalid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_24:any = (this._RequiredValidator_22_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementAttribute(this._el_22,'required',((currVal_24 == (null as any))? (null as any): currVal_24.toString()));
      this._expr_24 = currVal_24;
    }
    const currVal_26:any = this._NgControlStatus_22_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_22,'ng-untouched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_22_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_22,'ng-touched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_22_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_22,'ng-pristine',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_22_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_22,'ng-dirty',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_22_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_22,'ng-valid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_22_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_22,'ng-invalid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:boolean = !this.parent.context.myForm.valid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementProperty(this._el_31,'disabled',currVal_32);
      this._expr_32 = currVal_32;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_11_7.ngOnDestroy();
    this._FormControlName_22_7.ngOnDestroy();
  }
  private _handle_ngSubmit_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onSubmit(this._FormGroupDirective_0_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_0_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_0_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_11_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_11_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_11_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_22_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_22_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_22_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onCancel()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ProfileEditComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ProfileEditComponent1(viewUtils,parentInjector,declarationEl);
}